# -*- coding: utf-8 -*-
#"""
#Created on  Jul 24 16:13:25 2016-2017

#@author: Ankit Singh
#"""

# -*- coding: utf-8 -*-

#Created on  Jul 20 11:43:52 2016

#@author: Ankit Singh


WebsiteSupported:
   # - IndianExpress
   # - TheHindu
    - the-huffington-post
    - the-new-york-times
    - bbc-news
    - bloomberg
    - the-guardian-uk
    - the-hindu
    - the-times-of-india
   # - The WashingtonPost
   # - TheNewyorkTimes

#No of posts to be displayed in the one go    
Limit: 10

Apikey: bda5818cc2af461e98330ccdf6fb9cbe

    